$id: https://github.com/nqminds/Trusted-AI-BOM/blob/main/packages/schemas/src/trained-on.yaml
$schema: https://json-schema.org/draft/2019-09/schema
title: TAIBOM Training Weights
description: Declaration that the provided weights have been produced through training on the given data.
type: object
properties:
  name:
    type: string
    description: Human readable name for weights
  trainingSystem:
    description: Hash of the AI training pipeline.
    type: string
    anyOf:
      - format: url
        description: URI to the AI training pipeline hash
      - not:
          format: url
          description: Hash of the AI training pipeline
  weights:
    description: Hash of the weights produced by training data on an AI training pipeline.
    type: string
    anyOf:
      - format: url
        description: URI to the weights hash
      - not:
          format: url
          description: Hash of the weights
  data:
    description: Hash of the data used in training an AI system.
    type: string
    anyOf:
      - format: url
        description: URI to hashed data
      - not:
          format: url
          description: Hash of data
required:
  - weights
  - data
  - name
examples:
  - data: https://example.com/data/hash
    weights: https://example.com/weights/hash
    name: Weights v1
  - data: https://example.com/data/hash
    weights: https://example.com/weights/hash
    trainingSystem: https://example.com/trainingSystem/hash
    name: Weights v2
  - data: https://example.com/data/hash
    weights: 0677e4e34ac5f763991bd233890f0f845ed1e9de474595a507bfcff0c27d71fc
    trainingSystem: 67e6dfe22f36ce23f864336e2ed461574a49b4ee56f3eb0e1b0247e4f6d49375
    name: Weights v3
  - data: a5a67b39faf14d8dac7bab43ca1322ffa7f37551045d05393192f2f37e5be254
    weights: https://example.com/weights/hash
    name: Weights v4
  - data: a5a67b39faf14d8dac7bab43ca1322ffa7f37551045d05393192f2f37e5be254
    weights: 0677e4e34ac5f763991bd233890f0f845ed1e9de474595a507bfcff0c27d71fc
    trainingSystem: https://example.com/trainingSystem/hash
    name: Weights v5


