$id: https://github.com/nqminds/Trusted-AI-BOM/blob/main/packages/schemas/src/taibom-schemas/25-config.v1.0.0.schema.yaml
$schema: https://json-schema.org/draft/2019-09/schema
title: Trained System Configs
description: |
  This schema defines an AI system which may be used for Training AI models or an inferencing system, 
  with added cryptographic hashes for integrity verification.
type: object
properties:
  name:
    description: Name of the system config.
    type: string
  
  aiSystem:
    type: object
    properties:
      id:
        type: string
        description: ID of the AI system VC
      hash:
        type: string
        description: Cryptographic hash (e.g., SHA-256) of the AI system VC for verification
    required:
      - id
      - hash

  data:
    type: object
    properties:
      id:
        type: string
        description: ID of the weights which have been produced
      hash:
        type: string
        description: Cryptographic hash (e.g., SHA-256) of the data weights for verification
    required:
      - id
      - hash

required:
  - name
  - aiSystem
  - data

examples:
  - name: "AI Model Training System"
    aiSystem:
      id: "urn:uuid:1cdf9f5c-b62c-4493-868a-aiSystem-123"
      hash: "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
    data:
      id: "urn:uuid:1cdf9f5c-b62c-4493-868a-data-abcdefg"
      hash: "fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321"

context: |
  ## Introduction

  The **Trained System Configs Schema** is a JSON schema designed to define AI system configurations within the Trusted AI BOM (TAIBOM) ecosystem. These configurations are used to describe systems involved in training AI models or inferencing processes, ensuring clear traceability and alignment with associated datasets and systems.

  ### Description
  This schema captures essential metadata for trained system configurations, including:
  - **Name**: A unique identifier for the system configuration.
  - **AI System**: An object containing:
    - The unique ID of the AI system VC (Verifiable Credential).
    - A cryptographic hash (`hash`) to ensure the integrity of the referenced AI system VC.
  - **Data**: An object containing:
    - The unique ID of the weights produced or used by the system.
    - A cryptographic hash (`hash`) to ensure the integrity of the referenced data weights.

  ## Use Case

  The **Trained System Configs Schema** is primarily used within the TAIBOM framework to:
  1. **Document AI Systems**: Provide a standardised format for identifying and describing AI systems involved in training or inferencing.
  2. **Ensure Traceability**: Link AI systems to specific datasets and outputs (e.g., weights) for robust provenance tracking.
  3. **Verify Data Integrity**: Ensure the integrity of referenced AI systems and datasets through cryptographic hashes.
  4. **Support AI Lifecycle Management**: Enable seamless integration of system configurations into workflows for monitoring and validation.

  By adopting this schema, organisations can maintain clear and consistent documentation of their AI system configurations, supporting transparency, integrity, and accountability in AI development and deployment.

  ---
